#Demande des informations nécessaires à l'application de la formule de référence de Black & co
age = int(input("Combien d'années as-tu?\n"))
sexe = input("Es-tu biologiquement un homme ou une femme? (note H ou F)\n")
taille = float(input("Quelle est ta taille en mètre?\n"))
poids = float(input("Combien pèses-tu en kg?\n"))
activite = int(input("Si tu es sédentaire tape 1, si tu t'entraînes sportivement plus d'1h par semaine tape 2, si plus de 4h tape 3, au delà de 6h tape 4\n"))
#Application de l'équation de Black & co pour définir le métabolisme basal accompagné d'un coefficient correcteur d'activité physique
if sexe == "H" and activite == 1:
    print(f"Tu as besoin pour maintenir un poids stable d'environ {int(1.375 * 1.083 * (poids**0.48) * (taille**0.50) * (age**-0.13) * (1000/4.1855))} kCal par jour, fait varier de + ou - 200 kCal dans l'idéal ton apport de manière cyclique pour augmenter ou diminuer ton poids à niveau d'activité égale sans impacter négativement ta composition corporelle, à condition bien sûr de conserver en moyenne hebdomadaire les apports protéiques et lipidiques adaptés afin de maintenir tes fonctions hormonales y compris en diète hypocalorique")
elif sexe == "H" and activite == 2:
    print(f"Tu as besoin pour maintenir un poids stable d'environ {int(1.56 * 1.083 * (poids**0.48) * (taille**0.50) * (age**-0.13) * (1000/4.1855))} kCal par jour, fait varier de + ou - 200 kCal dans l'idéal ton apport de manière cyclique pour augmenter ou diminuer ton poids à niveau d'activité égale sans impacter négativement ta composition corporelle, à condition bien sûr de conserver en moyenne hebdomadaire les apports protéiques et lipidiques adaptés afin de maintenir tes fonctions hormonales y compris en diète hypocalorique")
elif sexe == "H" and activite == 3:
    print(f"Tu as besoin pour maintenir un poids stable d'environ {int(1.64 * 1.083 * (poids**0.48) * (taille**0.50) * (age**-0.13) * (1000/4.1855))} kCal par jour, fait varier de + ou - 200 kCal dans l'idéal ton apport de manière cyclique pour augmenter ou diminuer ton poids à niveau d'activité égale sans impacter négativement ta composition corporelle, à condition bien sûr de conserver en moyenne hebdomadaire les apports protéiques et lipidiques adaptés afin de maintenir tes fonctions hormonales y compris en diète hypocalorique")
elif sexe == "H" and activite == 4:
    print(f"Tu as besoin pour maintenir un poids stable d'environ {int(1.82 * 1.083 * (poids**0.48) * (taille**0.50) * (age**-0.13) * (1000/4.1855))} kCal par jour, fait varier de + ou - 200 kCal dans l'idéal ton apport de manière cyclique pour augmenter ou diminuer ton poids à niveau d'activité égale sans impacter négativement ta composition corporelle, à condition bien sûr de conserver en moyenne hebdomadaire les apports protéiques et lipidiques adaptés afin de maintenir tes fonctions hormonales y compris en diète hypocalorique")
elif sexe == "F" and activite == 1:
    print(f"Tu as besoin pour maintenir un poids stable d'environ {int(1.375 * 1.083 * (poids**0.48) * (taille**0.50) * (age**-0.13) * (1000/4.1855))} kCal par jour, fait varier de + ou - 200 kCal dans l'idéal ton apport de manière cyclique pour augmenter ou diminuer ton poids à niveau d'activité égale sans impacter négativement ta composition corporelle, à condition bien sûr de conserver en moyenne hebdomadaire les apports protéiques et lipidiques adaptés afin de maintenir tes fonctions hormonales y compris en diète hypocalorique")
elif sexe == "F" and activite == 2:
    print(f"Tu as besoin pour maintenir un poids stable d'environ {int(1.56 * 1.083 * (poids**0.48) * (taille**0.50) * (age**-0.13) * (1000/4.1855))} kCal par jour, fait varier de + ou - 200 kCal dans l'idéal ton apport de manière cyclique pour augmenter ou diminuer ton poids à niveau d'activité égale sans impacter négativement ta composition corporelle, à condition bien sûr de conserver en moyenne hebdomadaire les apports protéiques et lipidiques adaptés afin de maintenir tes fonctions hormonales y compris en diète hypocalorique")
elif sexe == "F" and activite == 3:
    print(f"Tu as besoin pour maintenir un poids stable d'environ {int(1.64 * 1.083 * (poids**0.48) * (taille**0.50) * (age**-0.13) * (1000/4.1855))} kCal par jour, fait varier de + ou - 200 kCal dans l'idéal ton apport de manière cyclique pour augmenter ou diminuer ton poids à niveau d'activité égale sans impacter négativement ta composition corporelle, à condition bien sûr de conserver en moyenne hebdomadaire les apports protéiques et lipidiques adaptés afin de maintenir tes fonctions hormonales y compris en diète hypocalorique")
elif sexe == "F" and activite == 4:
    print(f"Tu as besoin pour maintenir un poids stable d'environ {int(1.82 * 1.083 * (poids**0.48) * (taille**0.50) * (age**-0.13) * (1000/4.1855))} kCal par jour, fait varier de + ou - 200 kCal dans l'idéal ton apport de manière cyclique pour augmenter ou diminuer ton poids à niveau d'activité égale sans impacter négativement ta composition corporelle, à condition bien sûr de conserver en moyenne hebdomadaire les apports protéiques et lipidiques adaptés afin de maintenir tes fonctions hormonales y compris en diète hypocalorique")
